### ISSUE TITLE
请问post返回‘设备未注册,请在ePortal上添加认证设备’怎么解决？{"userIndex":null,"result":"fail","message":"设备未注册,请在ePortal上添加认证设备","forwordurl":null,"keepaliveInterval":0,"validCodeUrl":""}

### ISSUE THREAD

**Issue by Syucryingstar** [adeljck/ruijie#1]

**Comment by jinexplorer** [comment]
是querystring的问题，发现burpsuite的抓包querystring是浏览器url的二次url编码，但浏览器抓到的是一次url编码，正确的登录应该使用一次url编码

**Comment by jinexplorer** [comment]
之前确实burpsuite 二次编码的问题。我是之后就没有问题了，你在抓包改改试试看




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月21日(星期一) 晚上11:31
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [adeljck/ruijie] 请问post返回‘设备未注册,请在ePortal上添加认证设备’怎么解决？{&quot;userIndex&quot;:null,&quot;result&quot;:&quot;fail&quot;,&quot;message&quot;:&quot;设备未注册,请在ePortal上添加认证设备&quot;,&quot;forwordurl&quot;:null,&quot;keepaliveInterval&quot;:0,&quot;validCodeUrl&quot;:&quot;&quot;} (#1)





  
是querystring的问题，发现burpsuite的抓包querystring是浏览器url的二次url编码，但浏览器抓到的是一次url编码，正确的登录应该使用一次url编码
  
使用了一次url编码还是同样的报错，请问您是怎么解决的？
